name: C:\Anaconda\envs\python3
dependencies:
- anaconda-build=0.14.0=py35_0
- anaconda-client=1.2.2=py35_0
- beautifulsoup4=4.4.1=py35_0
- biopython=1.66=np110py35_0
- clyent=1.2.1=py35_0
- cycler=0.9.0=py35_0
- decorator=4.0.9=py35_0
- html5lib=0.999=py35_0
- ipykernel=4.2.2=py35_0
- ipython=4.1.1=py35_0
- ipython_genutils=0.1.0=py35_0
- ipywidgets=4.1.1=py35_0
- jinja2=2.8=py35_0
- jpeg=8d=vc14_0
- jsonschema=2.4.0=py35_0
- jupyter=1.0.0=py35_1
- jupyter_client=4.1.1=py35_0
- jupyter_console=4.1.0=py35_0
- jupyter_core=4.0.6=py35_0
- libpng=1.6.17=vc14_1
- libtiff=4.0.6=vc14_1
- lxml=3.5.0=py35_0
- markupsafe=0.23=py35_0
- matplotlib=1.5.1=np110py35_0
- mistune=0.7.1=py35_0
- msvc_runtime=1.0.1=vc14_0
- nbconvert=4.1.0=py35_0
- nbformat=4.0.1=py35_0
- networkx=1.11=py35_0
- notebook=4.1.0=py35_0
- numpy=1.10.1=py35_0
- openssl=1.0.2f=vc14_0
- pandas=0.17.1=np110py35_0
- path.py=8.1.2=py35_1
- pickleshare=0.5=py35_0
- pip=8.0.3=py35_0
- psutil=3.4.2=py35_0
- pygments=2.1=py35_0
- pymysql=0.6.7=py35_0
- pyparsing=2.0.3=py35_0
- pyqt=4.11.4=py35_4
- pyreadline=2.1=py35_0
- python=3.5.1=2
- python-dateutil=2.4.2=py35_0
- pytz=2015.7=py35_0
- pywin32=219=py35_2
- pyyaml=3.11=py35_2
- pyzmq=15.2.0=py35_0
- qt=4.8.7=vc14_5
- qtconsole=4.1.1=py35_0
- requests=2.9.1=py35_0
- scikit-learn=0.17=np110py35_1
- scipy=0.16.0=np110py35_0
- setuptools=20.1.1=py35_0
- simplegeneric=0.8.1=py35_0
- sip=4.16.9=py35_2
- six=1.10.0=py35_0
- tk=8.5.18=vc14_0
- tornado=4.3=py35_0
- traitlets=4.1.0=py35_0
- wheel=0.29.0=py35_0
- zlib=1.2.8=vc14_2
- pip:
  - ipython-genutils==0.1.0
  - jupyter-client==4.1.1
  - jupyter-console==4.1.0
  - jupyter-core==4.0.6
  - sphinx==1.3.1

